### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by EricGraham7** [aabu4537/Team3-Recitation13#8]
As a user, I want there to be certain common parts of each webpage that function and look exactly the same way. The partials should include a header, footer, menu, and possibly error message display to include on every page. 

Acceptance Criteria: Every page needing the information from the partials successfully displays it. For example, the "Home" page shows the footer from the "footers" partial.

**Comment by EricGraham7** [comment]
I noticed someone added me as an assignee to the partials, but I thought it was decided that I would do the API stuff?

**Comment by dmboynton56** [comment]
Uploaded partials. Done.
